### ISSUE TITLE
Practica TestRail

### ISSUE THREAD

**Issue by salathiel1999** [SistemasTecTlaxiaco/actividad-6-practica-de-calidad-de-testrail-con-wallet-dream-team1#1]
[TestRailG.pdf](https://github.com/SistemasTecTlaxiaco/actividad-6-practica-de-calidad-de-testrail-con-wallet-dream-team1/files/9717566/TestRailG.pdf)

**Comment by josealfredo79** [comment]
Calificacion: 18

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
